version: '3'
services: 
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes: 
      - /data:./data/db
    networks:
      - network
  nodejs:
    build: './'
    expose: 
      - 3000
    networks: 
      - network
    depends_on:
      - db

networks:
  network:
    driver: bridge