version: '3'
services: 
  db:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes: 
      - /data:/data/db
  nodejs:
    image: 'note-taking-app'
    command: npm run serve
    ports: 
      - "3000:3000"
    depends_on:
      - db
